name: Frontend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Validate HTML
        uses: chabad360/html-linter-action@v1
        with:
          files: "*.html"

      - name: Validate CSS
        uses: stylelint/stylelint-action@v1
        with:
          files: "**/*.css"

      - name: Validate JavaScript
        uses: denoland/setup-deno@v2
        with:
          deno-version: v1.x
      - run: deno lint

  
